export const SERACH_SQUASH = "SERACH_SQUASH";
export const SEARCH_SQUASH_SUCCESS = "SEARCH_SQUASH_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const STOP_API_CALL = "STOP_API_CALL";
export const SEARCH_BADMINTON_SUCCESS = "SEARCH_BADMINTON_SUCCESS";
