export const SERACH_SQUASH = "SERACH_SQUASH";
export const SEARCH_SQUASH_SUCCESS = "SEARCH_SQUASH_SUCCESS";
export const BEGIN_SQUASH_API_CALL = "BEGIN_SQUASH_API_CALL";
export const STOP_SQUASH_API_CALL = "STOP_SQUASH_API_CALL";
